### ISSUE TITLE
add option to suppress generating dialog.xml and _cq_dialog.xml

### ISSUE THREAD

**Issue by cmacioch** [OlsonDigital/cq-component-maven-plugin#44] opened 2016-07-21 19:53 UTC
Since some components don't need to be edited, there should be a way to suppress generating the dialog.xml and _cq_dialog.xml files.
There is a 'suppressTouchUIDialog' property on the Component annotation, but it only suppresses generation of the _cq_dialog.xml file and the dialog.xml is still there, even if there are no widgets to include inside the dialog.
Either providing another property to suppress generating dialog.xml or just not generating the files if there is nothing to show in the dialogs would fix the issue.

**Comment by michaelhodgdon** [comment] 2017-04-17 14:30
Closing as a duplicate of #58 and #59

**Closed by michaelhodgdon** 2017-04-17 14:30 UTC
